### ISSUE TITLE
Can F# community contribute `FSharp.Collections.SimdSeq` project to this repo with F# used function bindings?

### ISSUE THREAD

**Issue by xperiandri** [Cysharp/SimdLinq#8]
The idea is to create `FSharp.Collections.SimdSeq` project similar to https://github.com/fsprojects/FSharp.Collections.ParallelSeq/blob/main/src/FSharp.Collections.ParallelSeq/pseq.fs with F# specific function names and release together as `FSharp.Collections.SimdSeq` NuGet

**Comment by neuecc** [comment]
I have no interest in F#.
