### ISSUE TITLE
Integration with EfCore Linq

### ISSUE THREAD

**Issue by ziongh** [Cysharp/SimdLinq#9]
As this package overwrites the Linq methods, when it is used inside a query os a EfCore Context, the EfCore does not know how to translate into SQL.

For instance: 

```
var searchedIds = new List<int> {1,2,3};
await _context.SampleEntity.Where(s => searchedIds.Contains(s.Id))
                .ToListAsync();
```

It would be interesting to have the default implementation of "Contains" for the EfCore provider used into the functions. Eg.: now in EfCore the Include uses **OpenJson** in SQL, but could use the "IN (...)" expression.

I haven´t tried to implement it yet, but could be an Extension like:

```
     public static void ConfigureDbContainsSimd(this ModelBuilder modelBuilder)
	{
		var containsMethods = typeof(SimdLinqExtensions).GetMethods().Where(s => s.Name == "Contains").ToList();
		
		foreach (var containsMethod in containsMethods)
		{
			var dbFunction = modelBuilder.Model.FindDbFunction("Contains");
			if (dbFunction == null)
			{
				modelBuilder.HasDbFunction(containsMethod, b => new DbFunctionBuilder(dbFunction));
			}
		}
	} 
```

**Comment by neuecc** [comment]
I believe SIMD is completely unrelated to DB queries (Expression Trees)...?

**Comment by ziongh** [comment]
I actually got in some cases exceptions on the EfCore because it did now know how to translate the ```.Contains``` into SQL. And when I did a "Go to implementation" of the ```.Contains``` it took me to the SIMD package. So I imagine that the EfCore is trying to translate this, that why I proposed some kind of Mapping for the functions to the Database.

**Comment by neuecc** [comment]
Somewhere along the line, it likely became an IEnumerable.
